services:
  boardgames-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: boardgames-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_FLYWAY_SCHEMAS: ${SPRING_FLYWAY_SCHEMAS}
      APP_BASE_URL: ${APP_BASE_URL}
      APP_ASSETS_PATH: /app/data/assets
    volumes:
      - ${ASSETS_STORAGE_HOST_PATH}:/app/data/assets
