### GET game with expansions by bggId
GET {{host}}/api/games/173346

### GET last played game with expansions
GET {{host}}/api/games/last-played

### GET all games with expansions
GET {{host}}/api/games

### GET all games with expansions with filters and sorting
GET {{host}}/api/games?players=2&sort=ratingPersonal&dir=desc

### POST add game
POST {{host}}/api/games
Content-Type: application/json

{
  "bggId": 123456789,
  "name": "Test",
  "ratingBgg": 9.0,
  "ratingPersonal": null,
  "playingTimeMin": 30,
  "playingTimeMax": 60,
  "complexity": 2.5,
  "playersMin": 1,
  "playersMax": 4,
  "playersRecMin": 2,
  "playersRecMax": 3
}

### PUT update game
PUT {{host}}/api/games/123456789
Content-Type: application/json

{
  "bggId": 123456789,
  "name": "Test 2",
  "ratingBgg": 9.0,
  "ratingPersonal": 2,
  "playingTimeMin": 30,
  "playingTimeMax": 60,
  "complexity": 2.5,
  "playersMin": 1,
  "playersMax": 4,
  "playersRecMin": 2,
  "playersRecMax": 3
}

### DELETE game
DELETE {{host}}/api/games/123456789
