server:
  port: 8080
  servlet:
    context-path: /board-games

management:
  endpoint:
    health:
      show-details: never
  endpoints:
    web:
      exposure:
        include: health, info

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  web:
    error:
      include-message: always

  flyway:
    enabled: true
    schemas: ${SPRING_FLYWAY_SCHEMAS}

app:
  images:
    path: ${APP_IMAGES_PATH}
    public-base: /media

logging:
  level:
    root: info
    org.flywaydb: info
    org.springframework.web: info
    Exposed: info
